models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }
}

models/Post.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;

class Post extends ActiveRecord
{
    public static function tableName()
    {
        return "post";
    }

    public function rules()
    {
        return [
            [["title", "content", "author"], "required"],
            [["title", "content"], "trim"],
            [["title", "content"], "string", "length" => [1]],
        ];
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    public static function findNewest($n = 5)
    {
       return Post::find()
            ->orderBy("created_at DESC")
            ->limit($n)
            ->all();
    }

    public static function findAllOrderedByNewest()
    {
       return Post::find()
            ->orderBy("created_at DESC")
            ->all(); 
    }
}

models/User.php
<?php

namespace app\models;

use Yii;

use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends ActiveRecord implements IdentityInterface
{
    public static function tableName()
    {
        return "user";
    }

    const SCENARIO_LOGIN = "login";

    public function scenarios()
    {
        return [
            self::SCENARIO_LOGIN => ["username", "password"],
        ];
    }

    public function rules()
    {
        return [
            [["username", "password"], "required"],
            ["email", "email"]
        ];
    }

    /**
     * Finds an identity by the given ID.
     *
     * @param string|int $id the ID to be looked for
     * @return IdentityInterface|null the identity object that matches the given ID.
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * Finds an identity by the given token.
     *
     * @param string $token the token to be looked for
     * @return IdentityInterface|null the identity object that matches the given token.
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(["access_token" => $token]);
    }

    /**
     * Finds an identity by the given ID.
     *
     * @param string $username the Username to be looked for
     * @return IdentityInterface|null the identity object that matches the given Username.
     */
    public static function findByUsername($username)
    {
        return static::findOne(["username" => $username]);
    }

    /**
     * @return int|string current user ID
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string current user auth key
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @param string $authKey
     * @return bool if auth key is valid for current user
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * @param string $password
     * @return bool if password is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use yii\web\Controller;

use app\models\Post;

class PostController extends Controller
{
    /**
    * @inheritdoc
    */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays a post with the given ID.
     * @param int $id the id of the post to be shown
     * @return string
     */
    public function actionShow($id)
    {
        $post = Post::findOne($id);
        if($post === null) {
            throw new \yii\web\NotFoundHttpException();
        }

        return $this->render('post', [
            'post' => $post,
        ]);
    }

    /**
     * Displays all posts in an overview
     * 
     * @return string
     */
    public function actionIndex()
    {
        $posts = Post::findAllOrderedByNewest();
        return $this->render('posts', [
            'posts' => $posts,
        ]);
    }

    public function actionAll()
    {
        $posts = Post::find()->select(['id','title'])->all();
        
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        
        return $posts;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Post;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $posts = Post::findNewest(5);
        return $this->render('index', [
            'posts' => $posts,
        ]);
    }

    /**
     * Displays Search Result Page.
     *
     * @return string
     */
    public function actionSearch()
    {
        $request = Yii::$app->getRequest()->getQueryParam('searchField');
        $posts = Post::find()->where(['like', 'title', $request])->all();

        return $this->render('search', [
            'posts' => $posts,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Blog',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $items = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];

    if (!Yii::$app->user->isGuest) {
        $additionalItems = [
            ['label' => 'Admin', 'url' => ['/admin']],
            '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>'
        ];
    } else {
        $additionalItems = [
            ['label' => 'Login', 'url' => ['/site/login']],
        ];
    }

    $items = array_merge($items, $additionalItems);

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $items
    ]);

    echo '<form action="/search" method="get" class="navbar-form navbar-left">
        <div class="search form-group">
            <input type="text" id="searchField" name="searchField" class="form-control" placeholder="Search"/>
            <ul id="searchSuggests" class="list-unstyled"></ul>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>';

    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Blog <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/post/post.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = Html::encode($post->title);
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <a href="<?php echo Url::to(['post/show', 'id' => $post->id]); ?>">
                <?= Html::encode($post->title) ?>
            </a>
            from <?= Yii::$app->formatter->asDatetime ($post->created_at, 'yyyy-MM-dd HH:mm:ss') ?>
        </h3>
    </div>
    <div class="panel-body">
        <?= Html::encode($post->content) ?>
    </div>
</div>

views/post/posts.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = "Post Archive";
?>

<div class="site-index">
    <ul>
        <?php foreach($posts as $post) { ?>
            <li>
                <p>
                    <a href="<?php echo Url::to(['post/show', 'id' => $post->id]) ?>">
                        <?= Html::encode($post->title) ?>
                    </a>
                    from <?= Yii::$app->formatter->asDatetime ($post->created_at, 'yyyy-MM-dd HH:mm:ss') ?>
                </p>
            </li>
        <?php } ?>
    </ul>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'My Blog';
?>

<div class="site-index">
    <?php foreach($posts as $post) { ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?php echo Url::to(['post/show', 'id' => $post->id]); ?>">
                        <?= Html::encode($post->title) ?>
                    </a>
                </h3>
            </div>
            <div class="panel-body">
                <?= Html::encode($post->content) ?>
            </div>
        </div>
    <?php } ?>

    <a href="<?php echo Url::to(['post/']) ?>">Archive</a>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong>.
    </div>
</div>

views/site/search.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Search Result';
?>

<div class="site-index">
    <h1>Search Result</h1>
    <?php foreach($posts as $post) { ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?php echo Url::to(['post/show', 'id' => $post->id]); ?>">
                        <?= Html::encode($post->title) ?>
                    </a>
                </h3>
            </div>
            <div class="panel-body">
                <?= Html::encode($post->content) ?>
            </div>
        </div>
    <?php } ?>

    <a href="<?php echo Url::to(['post/']) ?>">Archive</a>
</div>