modules/admin/controllers/AbstractAdminController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\web\Controller;

abstract class AbstractAdminController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
}

modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use yii\web\Controller;

use app\modules\admin\controllers\AbstractAdminController;

class DefaultController extends AbstractAdminController
{
    public function actionIndex()
    {
        return $this->render('index');
    }
}

modules/admin/controllers/PostController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\web\Controller;

use app\models\Post;
use app\modules\admin\controllers\AbstractAdminController;
use app\modules\admin\models\PostForm;

class PostController extends AbstractAdminController
{
    /**
     * If GET: Displays a post with the given $id for the admin.
     * If POST: updates the post with the given $id and then displays it.
     * @param int $id the id of the post to be shown/saved
     * @return string
     */
    public function actionShow($id)
    {
        $post = Post::findOne($id);
        if($post === null) {
            throw new \yii\web\NotFoundHttpException();
        }

        if(Yii::$app->request->post()) {
            $post->load(Yii::$app->request->post());
            $post->author = Yii::$app->user->id;

            if ($post->validate() && $post->update()) {
                $this->redirect(['index']);
            }
        }

        return $this->render("post", [
            "post" => $post,
        ]);
    }

    public function actionCreate()
    {
        $post = new Post();

        if(Yii::$app->request->post()) {
            $post->load(Yii::$app->request->post());
            $post->author = Yii::$app->user->id;

            if ($post->validate() && $post->save()) {
                $this->redirect(['index']);
            }
        }

        return $this->render("post", [
            "post" => $post,
        ]);        
    }

    public function actionDelete($id)
    {
        $post = Post::findOne($id);
        if($post === null) {
            throw new \yii\web\NotFoundHttpException();
        }

        $post->delete();

        $this->redirect(['index']);       
    }

    /**
     * Displays all posts in an overview
     * 
     * @return string
     */
    public function actionIndex()
    {
        $posts = Post::findAllOrderedByNewest();
        if(empty($posts)) {
            throw new \yii\web\NotFoundHttpException();
        }

        return $this->render("posts", [
            "posts" => $posts,
        ]);
    }
}

modules/admin/views/default/index.php
<?php
use yii\helpers\Url;

/* @var $this yii\web\View */
?>

<div class="site-index">
    <a href="<?= Url::to(['post/']) ?>">Posts</a>
</div>

modules/admin/views/post/post.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
    'id' => 'login-form',
    'options' => ['class' => 'form-horizontal'],
]) ?>

<div class="col-lg-12">
    <?= $form->field($post, 'title') ?>
    <?= $form->field($post, 'content')->textarea(["rows" => 6]) ?>

    <a href="<?= Url::to(['post/delete/'.$post->id]) ?>"><button type="button" class="btn btn-danger pull-left">Delete</button>
    <button type="submit" class="btn btn-success pull-right">Save</button>
</div>
<?php ActiveForm::end() ?>

modules/admin/views/post/posts.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = "Post Archive";
?>

<div class="site-index">
    <a href="<?= Url::to(['post/create']) ?>" class="pull-right"><button type="button" class="btn btn-success">Create a new Blog Post</button></a>
    
    <ul>
        <?php foreach($posts as $post) { ?>
            <li>
                <a href="<?= Url::to(['/admin/post/'.$post->id]) ?>">
                    <?= Html::encode($post->title) ?>
                </a>
            </li>
        <?php } ?>
    </ul>
</div>